language: ruby
sudo: false
dist: trusty
rvm:
  - 2.4.2
services:
  - docker

before_install:
  - echo "before_install"

install:
  - echo "install"
  - gem install bundler --no-rdoc --no-ri
  - bundle install

before_script:
  - echo 'before_script'
  - export TF_VAR_region=us-west-2; export AWS_REGION=us-west-2
  - wget https://releases.hashicorp.com/terraform/0.10.6/terraform_0.10.6_linux_amd64.zip
  - unzip terraform_0.10.6_linux_amd64
  - chmod +x terraform
  - mkdir -p ${HOME}/bin
  - export PATH=${PATH}:${HOME}/bin
  - mv terraform ${HOME}/bin/
  - rm -f terraform_*
  - terraform -v

script:
  - echo 'before_script'
  - docker run -i -t -v $(pwd):/app/ -w /app/ hashicorp/terraform:light init
  - docker run -i -t -v $(pwd):/app/ -w /app/ hashicorp/terraform:light fmt -check=true
  - docker run -i -t -v $(pwd):/app/ -w /app/ hashicorp/terraform:light validate
  # - terraform init
  # - terraform fmt -check=true
  # - terraform validate
  - docker run --rm -v $(pwd):/data --workdir=/data -t wata727/tflint --error-with-issues
  - cd examples/test_fixtures
  # this line is to change the source of the root module to 2 dirs back which works when validating in CI but when running through test kitchen, we need 3 dirs up oddly
  - sed -i.bak 's/source = \"\.\.\//source = \"/g' main.tf
  - docker run -i -t -v $(pwd):/app/ -w /app/ hashicorp/terraform:light init
  - docker run -i -t -v $(pwd):/app/ -w /app/ hashicorp/terraform:light fmt -check=true
  - docker run -i -t -v $(pwd):/app/ -w /app/ hashicorp/terraform:light validate
  # - terraform init
  # - terraform fmt -check=true
  # - terraform validate
  - docker run --rm -v $(pwd):/data --workdir=/data -t wata727/tflint --error-with-issues # not working here yet
  - mv main.tf.bak main.tf
  - cd -
  - kitchen test --destroy always

# after_success:
#   - echo 'foo'

# after_failure:
#   - echo 'foo'

before_deploy:
# create new release in github? check if this is new release?
  - echo 'before_deploy phase'

deploy:
  provider: script
  script: ci/deploy.sh
  on:
    branch: dev

# after_deploy:
#   - echo 'foo'

# after_script:
#   - echo 'foo'
