language: ruby
sudo: false
rvm:
  # - 2.4.2
  - 2.2.0

before_install:
  # - install terraform
  - echo "before install"

install:
  - gem install bundler --no-rdoc --no-ri
  - bundle install

before_script:
  # - docker pull hashicorp/terraform:light
  - wget https://releases.hashicorp.com/terraform/0.10.6/terraform_0.10.6_linux_amd64.zip
  - unzip terraform_0.10.6_linux_amd64
  - chmod +x terraform
  - echo ${PATH}
  - mv terraform /usr/local/bin/
  - terraform -v
  - docker run -i -t -v $(pwd):/app/ -w /app/ hashicorp/terraform:light init
  - docker run -i -t -v $(pwd):/app/ -w /app/ hashicorp/terraform:light fmt -check=true
  - docker run -i -t -v $(pwd):/app/ -w /app/ hashicorp/terraform:light validate
  - echo 'before script'

script:
  - kitchen test --destroy always

# after_success:
#   - echo 'foo'

# after_failure:
#   - echo 'foo'

before_deploy:
# create new release in github? check if this is new release?
  - echo 'before_deploy phase'

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: dev

# after_deploy:
#   - echo 'foo'

# after_script:
#   - echo 'foo'
