language: ruby
sudo: false
dist: trusty
rvm:
  - 2.4.2
  # - 2.2.0 # necessary for docker

before_install:
  - echo "before_install"
  # - install terraform

install:
  - echo "install"
  - gem install bundler --no-rdoc --no-ri
  - bundle install
  - wget https://releases.hashicorp.com/terraform/0.10.6/terraform_0.10.6_linux_amd64.zip
  - unzip terraform_0.10.6_linux_amd64
  - chmod +x terraform
  - mkdir -p ${HOME}/bin
  - export PATH=${PATH}:${HOME}/bin
  - mv terraform ${HOME}/bin/
  - terraform -v

before_script:
  - echo 'before_script'
  - TF_VARS_region=us-west-2
  - TF_VARS="-var 'region=us-west-2'"
  - echo ${TF_VARS}
  - env
  - echo 'region = "us-west-2"' > terraform.tfvars
  - terraform init
  - terraform fmt -check=true
  - terraform validate
  - cd examples/test_fixtures
  - echo 'region = "us-west-2"' > terraform.tfvars
  - sed -i.bak 's/source = \"\.\.\//source = \"/g' main.tf # 3 dirs back to 2
  - terraform init
  - terraform fmt -check=true
  - terraform validate -var 'region=us-west-2'
  - mv main.tf.bak main.tf

script:
  - echo 'before_script'
  - kitchen test --destroy always

# after_success:
#   - echo 'foo'

# after_failure:
#   - echo 'foo'

before_deploy:
# create new release in github? check if this is new release?
  - echo 'before_deploy phase'


deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: dev

# after_deploy:
#   - echo 'foo'

# after_script:
#   - echo 'foo'
