language: ruby
sudo: false
dist: trusty
rvm:
  - 2.4.2
  # - 2.2.0 # necessary for docker

before_install:
  - echo "before_install"
  # - install terraform

install:
  - echo "install"
  - gem install bundler --no-rdoc --no-ri
  - bundle install
  - wget https://releases.hashicorp.com/terraform/0.10.6/terraform_0.10.6_linux_amd64.zip
  - unzip terraform_0.10.6_linux_amd64
  - chmod +x terraform
  - mkdir -p ${HOME}/bin
  - export PATH=${PATH}:${HOME}/bin
  - mv terraform ${HOME}/bin/
  - terraform -v

before_script:
  - echo 'before_script'
  - export TF_VAR_region="us-west-2"
  - terraform init
  - terraform fmt -check=true
  - terraform validate
  - cd examples/test_fixtures
  - sed -i.bak 's/source = \"\.\.\//source = \"/g' main.tf # 3 dirs back to 2
  - terraform init
  - terraform fmt -check=true
  - terraform validate
  - mv main.tf.bak main.tf

script:
  - echo 'before_script'
  - export TF_VAR_region="us-west-2"
  - kitchen test --destroy always

# after_success:
#   - echo 'foo'

# after_failure:
#   - echo 'foo'

before_deploy:
# create new release in github? check if this is new release?
  - echo 'before_deploy phase'


deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: dev

# after_deploy:
#   - echo 'foo'

# after_script:
#   - echo 'foo'
